# Generated by Django 4.2.29 on 2026-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
